name: Build & Publish Beta

on:
    push:
        paths:
            - 'src/**'
            - 'build/**'
            - 'samples/**'
    workflow_dispatch:

jobs:
  BuildAndPublish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Extract Version
      shell: pwsh
      run: |
        $versionSuffix = "-beta-"+$Env:GITHUB_RUN_NUMBER
        echo "VERSION_SUFFIX=$versionSuffix"
        echo "VERSION_SUFFIX=$versionSuffix" >> $Env:GITHUB_ENV
        $version = select-string -Path 'Directory.Build.Props' -Pattern '<VersionPrefix>(.*)<\/VersionPrefix>' -AllMatches | % { $_.Matches } | % { $_.Groups[1].Value }
        $version += $versionSuffix
        echo "VERSION=$version"
        echo "VERSION=$version" >> $Env:GITHUB_ENV
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Test
      run: dotnet test build\Myra.MonoGame.sln --verbosity normal
    - name: Build & Pack Myra.MonoGame
      run: dotnet pack build\Myra.MonoGame.sln --configuration Release --version-suffix ${{env.VERSION_SUFFIX}}
    - name: Build & Pack Myra.Stride
      run: dotnet pack build\Myra.Stride.sln --configuration Release --version-suffix ${{env.VERSION_SUFFIX}}
    - name: Build & Pack Myra.PlatformAgnostic
      run: dotnet pack build\Myra.PlatformAgnostic.sln --configuration Release --version-suffix ${{env.VERSION_SUFFIX}}
    - name: Build Binary Distribution
      shell: pwsh
      run: ./buildBinaryDistribution.ps1 ${{env.VERSION}}
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Myra.${{env.VERSION}}.zip
        path: Myra.${{env.VERSION}}.zip
        retention-days: 30
    - name: Publish Myra.MonoGame to nuget.org
      run: dotnet nuget push src\Myra\bin\MonoGame\Release\JKMP.Myra.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}} --skip-duplicate
    - name: Publish Myra.Stride to nuget.org
      run: dotnet nuget push src\Myra\bin\Stride\Release\JKMP.Myra.Stride.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}} --skip-duplicate
    - name: Publish Myra.PlatformAgnostic to nuget.org
      run: dotnet nuget push src\Myra\bin\PlatformAgnostic\Release\JKMP.Myra.PlatformAgnostic.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}} --skip-duplicate